<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Custom_field extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Custom_field_model');
    } 

    /*
     * Listing of custom_fields
     */
    function index()
    {
        $data['custom_fields'] = $this->Custom_field_model->get_all_custom_fields();
        
        $data['_view'] = 'custom_field/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new custom_field
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'is_required' => $this->input->post('is_required'),
				'is_filter' => $this->input->post('is_filter'),
				'is_searcheable' => $this->input->post('is_searcheable'),
				'is_multiple' => $this->input->post('is_multiple'),
				'type' => $this->input->post('type'),
				'name' => $this->input->post('name'),
				'default_value' => $this->input->post('default_value'),
				'possible_values' => $this->input->post('possible_values'),
            );
            
            $custom_field_id = $this->Custom_field_model->add_custom_field($params);
            redirect('custom_field/index');
        }
        else
        {            
            $data['_view'] = 'custom_field/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a custom_field
     */
    function edit($id)
    {   
        // check if the custom_field exists before trying to edit it
        $data['custom_field'] = $this->Custom_field_model->get_custom_field($id);
        
        if(isset($data['custom_field']['id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'is_required' => $this->input->post('is_required'),
					'is_filter' => $this->input->post('is_filter'),
					'is_searcheable' => $this->input->post('is_searcheable'),
					'is_multiple' => $this->input->post('is_multiple'),
					'type' => $this->input->post('type'),
					'name' => $this->input->post('name'),
					'default_value' => $this->input->post('default_value'),
					'possible_values' => $this->input->post('possible_values'),
                );

                $this->Custom_field_model->update_custom_field($id,$params);            
                redirect('custom_field/index');
            }
            else
            {
                $data['_view'] = 'custom_field/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The custom_field you are trying to edit does not exist.');
    } 

    /*
     * Deleting custom_field
     */
    function remove($id)
    {
        $custom_field = $this->Custom_field_model->get_custom_field($id);

        // check if the custom_field exists before trying to delete it
        if(isset($custom_field['id']))
        {
            $this->Custom_field_model->delete_custom_field($id);
            redirect('custom_field/index');
        }
        else
            show_error('The custom_field you are trying to delete does not exist.');
    }
    
}
