<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tracker extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Tracker_model');
    } 

    /*
     * Listing of trackers
     */
    function index()
    {
        $data['trackers'] = $this->Tracker_model->get_all_trackers();
        
        $data['_view'] = 'tracker/index';
        $this->load->view('layouts/main',$data);
    }

    /*
     * Adding a new tracker
     */
    function add()
    {   
        if(isset($_POST) && count($_POST) > 0)     
        {   
            $params = array(
				'is_custom' => $this->input->post('is_custom'),
				'is_useable' => $this->input->post('is_useable'),
				'name' => $this->input->post('name'),
            );
            
            $tracker_id = $this->Tracker_model->add_tracker($params);
            redirect('tracker/index');
        }
        else
        {            
            $data['_view'] = 'tracker/add';
            $this->load->view('layouts/main',$data);
        }
    }  

    /*
     * Editing a tracker
     */
    function edit($tracker_id)
    {   
        // check if the tracker exists before trying to edit it
        $data['tracker'] = $this->Tracker_model->get_tracker($tracker_id);
        
        if(isset($data['tracker']['tracker_id']))
        {
            if(isset($_POST) && count($_POST) > 0)     
            {   
                $params = array(
					'is_custom' => $this->input->post('is_custom'),
					'is_useable' => $this->input->post('is_useable'),
					'name' => $this->input->post('name'),
                );

                $this->Tracker_model->update_tracker($tracker_id,$params);            
                redirect('tracker/index');
            }
            else
            {
                $data['_view'] = 'tracker/edit';
                $this->load->view('layouts/main',$data);
            }
        }
        else
            show_error('The tracker you are trying to edit does not exist.');
    } 

    /*
     * Deleting tracker
     */
    function remove($tracker_id)
    {
        $tracker = $this->Tracker_model->get_tracker($tracker_id);

        // check if the tracker exists before trying to delete it
        if(isset($tracker['tracker_id']))
        {
            $this->Tracker_model->delete_tracker($tracker_id);
            redirect('tracker/index');
        }
        else
            show_error('The tracker you are trying to delete does not exist.');
    }
    
}
