<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Version extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Version_model');
    } 

    /*
     * Listing of versions
     */
    function index()
    {
        $data['versions'] = $this->Version_model->get_all_versions();
        
        $data['_view'] = 'version/index';
        $this->load->view('layouts/main',$data);
    }
}
