<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Versions_custom extends CI_Controller{
    function __construct()
    {
        parent::__construct();
        $this->load->model('Versions_custom_model');
    } 

    /*
     * Listing of versions_custom
     */
    function index()
    {
        $data['versions_custom'] = $this->Versions_custom_model->get_all_versions_custom();
        
        $data['_view'] = 'versions_custom/index';
        $this->load->view('layouts/main',$data);
    }
}
