<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Commentary_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get commentary by id
     */
    function get_commentary($id)
    {
        return $this->db->get_where('commentaries',array('id'=>$id))->row_array();
    }
    
    function get_issue_commentary($id)
    {
        return $this->db->get_where('commentaries',array('issue_id'=>$id))->result_array();
    }
        
    /*
     * Get all commentaries
     */
    function get_all_commentaries()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('commentaries')->result_array();
    }
        
    /*
     * function to add new commentary
     */
    function add_commentary($params)
    {
        $this->db->insert('commentaries',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update commentary
     */
    function update_commentary($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('commentaries',$params);
    }
    
    /*
     * function to delete commentary
     */
    function delete_commentary($id)
    {
        return $this->db->delete('commentaries',array('id'=>$id));
    }
}
