<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Custom_value_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get custom_value by id
     */
    function get_custom_value($id)
    {
        return $this->db->get_where('custom_values',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all custom_values
     */
    function get_all_custom_values()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('custom_values')->result_array();
    }
        
    /*
     * function to add new custom_value
     */
    function add_custom_value($params)
    {
        $this->db->insert('custom_values',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update custom_value
     */
    function update_custom_value($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('custom_values',$params);
    }
    
    /*
     * function to delete custom_value
     */
    function delete_custom_value($id)
    {
        return $this->db->delete('custom_values',array('id'=>$id));
    }
}
