<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Status_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get status by id
     */
    function get_status($id)
    {
        return $this->db->get_where('statuses',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all statuses
     */
    function get_all_statuses()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('statuses')->result_array();
    }
        
    /*
     * function to add new status
     */
    function add_status($params)
    {
        $this->db->insert('statuses',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update status
     */
    function update_status($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('statuses',$params);
    }
    
    /*
     * function to delete status
     */
    function delete_status($id)
    {
        return $this->db->delete('statuses',array('id'=>$id));
    }
}
