<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Tracker_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get tracker by tracker_id
     */
    function get_tracker($tracker_id)
    {
        return $this->db->get_where('trackers',array('tracker_id'=>$tracker_id))->row_array();
    }
        
    /*
     * Get all trackers
     */
    function get_all_trackers()
    {
        $this->db->order_by('tracker_id', 'desc');
        return $this->db->get('trackers')->result_array();
    }
        
    /*
     * function to add new tracker
     */
    function add_tracker($params)
    {
        $this->db->insert('trackers',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update tracker
     */
    function update_tracker($tracker_id,$params)
    {
        $this->db->where('tracker_id',$tracker_id);
        return $this->db->update('trackers',$params);
    }
    
    /*
     * function to delete tracker
     */
    function delete_tracker($tracker_id)
    {
        return $this->db->delete('trackers',array('tracker_id'=>$tracker_id));
    }
}
