<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Trackers_federated_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get trackers_federated by id
     */
    function get_trackers_federated($id)
    {
        return $this->db->get_where('trackers_federated',array('id'=>$id))->row_array();
    }
        
    /*
     * Get all trackers_federated
     */
    function get_all_trackers_federated()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('trackers_federated')->result_array();
    }
        
    /*
     * function to add new trackers_federated
     */
    function add_trackers_federated($params)
    {
        $this->db->insert('trackers_federated',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update trackers_federated
     */
    function update_trackers_federated($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('trackers_federated',$params);
    }
    
    /*
     * function to delete trackers_federated
     */
    function delete_trackers_federated($id)
    {
        return $this->db->delete('trackers_federated',array('id'=>$id));
    }
}
