<?php
/* 
 * Generated by CRUDigniter v3.2 
 * www.crudigniter.com
 */
 
class Version_model extends CI_Model
{
    function __construct()
    {
        parent::__construct();
    }
    
    /*
     * Get version by id
     */
    function get_version($id)
    {
        return $this->db->get_where('versions',array('id'=>$id))->row_array();
    }
    
    function get_version_issue($issue_id)
    {
        return $this->db->get_where('versions',array('issue_id'=>$issue_id))->result_array();
    }
        
    /*
     * Get all versions
     */
    function get_all_versions()
    {
        $this->db->order_by('id', 'desc');
        return $this->db->get('versions')->result_array();
    }
        
    /*
     * function to add new version
     */
    function add_version($params)
    {
        $this->db->insert('versions',$params);
        return $this->db->insert_id();
    }
    
    /*
     * function to update version
     */
    function update_version($id,$params)
    {
        $this->db->where('id',$id);
        return $this->db->update('versions',$params);
    }
    
    /*
     * function to delete version
     */
    function delete_version($id)
    {
        return $this->db->delete('versions',array('id'=>$id));
    }
}
